version: '3.8'
services:
  nginx:
    build:
      context: ./infra/
      args:
        BUILD_ARGUMENT_ENV: dev
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./crud_symfony:/var/www/html:ro,cached
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - symfony
    networks:
      - symfony

  symfony:
    build:
      context: ./infra/
      dockerfile: ./php/Dockerfile
    volumes:
      - ./crud_symfony:/var/www/html:cached
      - ./infra/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./infra/php/config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - symfony

  mysql:
    image: mysql
    command: --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1} --sql_mode=${SQL_MODE:-"ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"}
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: crm
    ports:
      - "3010:3306"
    volumes:
      - mysql:/var/lib/mysql:delegated
    networks:
      - symfony

  myadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - symfony
    volumes:
      - db_admin_data:/var/www/html

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - symfony

volumes:
  db_admin_data:
  mysql:

networks:
  symfony:
    name: symfony